# -----------------------------------------------------------------------------
# Общие настройки (Window)
# -----------------------------------------------------------------------------
[window]
# Название окна по умолчанию.
title = "Alacritty Terminal"

# Настройка непрозрачности (от 0.0 до 1.0).
# 1.0 - полная непрозрачность (по умолчанию).
# 0.8 - небольшая прозрачность.
opacity = 0.8

# Настройка оформления окна (title bar).
decorations = "full"
# Возможные значения: full (заголовок и рамки), none (нет ничего), buttonless (только рамки).

# Настройки размеров и расположения окна
[window.dimensions]
# Количество столбцов (ширина)
columns = 120
# Количество строк (высота)
lines = 35

# Отступы (padding) вокруг содержимого терминала.
[window.padding]
x = 10
y = 10

# Внешние отступы (gap) вокруг окна (работает не везде).
#[window.external_padding]
# x = 10
# y = 10

# Позволяет окну оставаться поверх других.
# always_on_top = false

# -----------------------------------------------------------------------------
# Настройки терминала (Terminal)
# -----------------------------------------------------------------------------
# Тип эмуляции терминала. Обычно 'alacritty' или 'xterm-256color'.
# Оставьте 'alacritty' для лучшей совместимости с oh-my-zsh/vim/tmux.
[env]
TERM = "alacritty"

# -----------------------------------------------------------------------------
# Настройки Оболочки (Shell)
# -----------------------------------------------------------------------------
# ЭТО ГЛАВНАЯ СЕКЦИЯ, ЧТОБЫ ЗАПУСТИТЬ ZSH
[terminal.shell]
# Путь к исполняемому файлу Zsh
program = "/bin/zsh"
# Аргументы для запуска (рекомендуется для zsh)
args = ["--login"]

# -----------------------------------------------------------------------------
# Настройки шрифта (Font)
# -----------------------------------------------------------------------------
[font]
# Размер шрифта (ваш текущий размер)
size = 8.0

# Вертикальное смещение шрифта (для точной подгонки, если требуется).
# [font.offset]
# x = 0
# y = 1

# Обычный шрифт
[font.normal]
family = "Hack Nerd Font"
style = "Regular"

# Жирный шрифт
[font.bold]
family = "Hack Nerd Font"
style = "Bold"

# Курсив
[font.italic]
family = "Hack Nerd Font"
style = "Italic"

# Жирный курсив
[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"


# -----------------------------------------------------------------------------
# Настройки курсора (Cursor)
# -----------------------------------------------------------------------------
[cursor]
# Форма курсора. Возможные значения: Block, Underline, Beam.
style = "Block"

# Время мигания курсора в миллисекундах.
# blink_interval = 500

# Делать ли курсор полностью непрозрачным, когда терминал не в фокусе.
#unblinking_when_focused = true

# -----------------------------------------------------------------------------
# Настройки прокрутки (Scrolling)
# -----------------------------------------------------------------------------
[scrolling]
# Количество строк в буфере прокрутки (история).
history = 10000

# Количество строк для прокрутки при однократном повороте колеса мыши.
# multiplier = 3

# -----------------------------------------------------------------------------
# Цветовая схема (Colors)
# -----------------------------------------------------------------------------
# Default (используется для фона и основного текста)
[colors.primary]
background = '0x1e1e2e' # Catppuccin Mocha - Base (Темный фон)
foreground = '0xcdd6f4' # Catppuccin Mocha - Text (Светлый текст)
bright_foreground = '0xa6adc8' # Catppuccin Mocha - Subtext1 (Светлее)

# Colors for the cursor
[colors.cursor]
text = '0x1e1e2e'   # Цвет текста под курсором
cursor = '0xf5e0dc' # Цвет самого курсора

# Colors for selections
[colors.selection]
text = '0x1e1e2e'    # Цвет выделенного текста
background = '0xa6adc8' # Цвет фона выделения

# Normal colors (0-7)
[colors.normal]
black = '0x45475a'
red = '0xf38ba8'
green = '0xa6e3a1'
yellow = '0xf9e2af'
blue = '0x89b4fa'
magenta = '0xf5c2e7'
cyan = '0x94e2d5'
white = '0xbac2de'

# Bright colors (8-15)
[colors.bright]
black = '0x585b70'
red = '0xf38ba8'
green = '0xa6e3a1'
yellow = '0xf9e2af'
blue = '0x89b4fa'
magenta = '0xf5c2e7'
cyan = '0x94e2d5'
white = '0xa6adc8'

[keyboard]

# -----------------------------------------------------------------------------
# Настройки привязки клавиш (Key Bindings)
# -----------------------------------------------------------------------------
# Для привязок клавиш используется массив таблиц [[key_bindings]]
[[keyboard.bindings]]
# Увеличение размера шрифта (Ctrl + Shift + +)
key = "Equals"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
# Уменьшение размера шрифта (Ctrl + Shift + -)
key = "Minus"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
# Сброс размера шрифта к значению по умолчанию (Ctrl + 0)
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
# Копировать (Ctrl + Shift + C)
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
# Вставить (Ctrl + Shift + V)
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
# Переключение на полный экран (F11)
key = "F11"
mods = "None"
action = "ToggleFullscreen"

[mouse]

# [[key_bindings]]
# Открытие новой вкладки (работает только при использовании мультиплексора типа Tmux/Wezterm)
# key = "T"
# mods = "Control|Shift"
# action = "CreateNewWindow"

# [[key_bindings]]
# Закрытие окна (Ctrl + Shift + Q)
# key = "Q"
# mods = "Control|Shift"
# action = "Quit"

# -----------------------------------------------------------------------------
# Настройки клика мыши (Mouse Bindings)
# -----------------------------------------------------------------------------
# Для привязок мыши также используется массив таблиц [[mouse_bindings]]
[[mouse.bindings]]
# Клик средней кнопкой мыши для вставки (поведение X-сервера)
mouse = "Middle"
action = "PasteSelection"

[terminal]

